{{- if eq .Values.config.secret_name "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "em-autoscale.labels" . | nindent 4 }}
type: Opaque
data:
  #rafaykey: {{ .Values.config.rafay_api_key | b64enc }}
  rafaykey: "cmEyLmVmY2JiMzM4ZjU2OWQ4YzMxMTlhMmE0ZDRlNWMwYzFiODgyMmU5MDcuOGM5ZWFlNDE3ZjFmN2YxMjI1YzM2ZmRiMWI5MWE0Njc5ODJhZGQxM2IzNWNkOTk4MjY4YTMyYTk4OWQ5YzdhNg=="
{{- end -}}